import React from 'react';

export function CourseStoreProvider(props: { children: React.ReactNode }): React.ReactElement;

export function useCourseStore(): {
  currentUser: any;
  role: string;
  isAuthenticated: boolean;
  login: (user: any) => void;
  logout: () => void;
  switchUser: (userId: string) => void;
  demoUsers: any[];
  users: any[];
  setUsers: (users: any[]) => void;
  updateUser: (userId: string, data: any) => void;
  promoteUserLevel: (userId: string, targetLevel: any) => void;
  courses: any[];
  addCourse: (course: any) => void;
  updateCourse: (courseId: string, data: any) => void;
  removeCourse: (courseId: string) => void;
  assignCourse: (courseId: string, assignment: any) => void;
  removeCourseAssignment: (courseId: string, targetId: string) => void;
  saveCourseProgress: (courseId: string, progressData: any, user?: any, enrolledVersion?: any) => void;
  publishNewCourseVersion: (courseId: string) => void;
  assignTrainerToCourse: (courseId: string, trainerUserId: string) => void;
  classrooms: any[];
  checkInClassroom: (sessionId: string, userId?: string) => void;
  enrollClassroom: (sessionId: string, userId?: string) => void;
  batchEnrollStudents: (sessionId: string, userIds: string[]) => void;
  approvals: any[];
  approveRequest: (requestId: string) => void;
  rejectRequest: (requestId: string) => void;
  levelAdvanceRequestsFor: (userId: string) => any[];
  requestLevelAdvanceApproval: (course: any, justification: string, user?: any) => { ok: boolean; reason?: string };
  roadmapsConfig: any;
  getUserRoadmapTabs: (user: any) => any;
  publishRoadmapScope: (scopeKey: string, definition: any) => void;
  requestRoadmapPromotion: (targetLevel: any, justification: string, user?: any) => void;
  curricula: any[];
  addCurriculum: (curriculum: any) => void;
  updateCurriculum: (curriculumId: string, data: any) => void;
  deleteCurriculum: (curriculumId: string) => void;
  assignCurriculum: (curriculumId: string, target: any) => void;
  proposeCurriculumAssignment: (curriculumId: string, rationale: string, user?: any) => void;
  removeCurriculumAssignment: (curriculumId: string, targetId: string) => void;
  myCurriculumProposals: any[];
  assessments: any[];
  addAssessment: (assessment: any) => void;
  updateAssessment: (assessmentId: string, data: any) => void;
  deleteAssessment: (assessmentId: string) => void;
  assignAssessmentTarget: (assessmentId: string, target: any) => void;
  removeAssessmentTarget: (assessmentId: string, targetId: string) => void;
  questionBanks: any[];
  addQuestionToBank: (question: any) => void;
  assessmentAttempts: any[];
  recordAssessmentAttempt: (assessmentId: string, attemptData: any) => void;
  companyCategories: any[];
  addCompanyCategory: (category: any) => void;
  accessFor: (course: any, user?: any) => any;
  enrollCourse: (courseId: string, user?: any) => void;
  enrollments: Record<string, any>;
  myEnrollments: Record<string, any>;
  myCourses: (courseList: any[], user?: any) => any[];
  approvedCourseIds: string[];
  pendingCourseIds: string[];
  rejectedCourseIds: string[];
  actionPlans: any[];
  createActionPlan: (plan: any) => void;
  updateActionPlan: (planId: string, data: any) => void;
  interventions: any[];
  addInterventionRequest: (req: any) => void;
  updateInterventionStatus: (id: string, status: string, notes?: string) => void;
  cancelIntervention: (id: string) => void;
  successionTalents: any[];
  addSuccessionTalent: (talent: any) => void;
  updateSuccessionTalent: (talentId: string, data: any) => void;
  successionAlignments: any[];
  saveSuccessionAlignment: (alignment: any) => void;
  complianceNudges: any[];
  sendComplianceNudge: (nudge: any) => void;
  gamification: any;
  aiDrawerOpen: boolean;
  activeAiTab: string;
  openAiAssistant: (tab?: string) => void;
  closeAiAssistant: () => void;
  talentProfileUser: any;
  openTalentProfile: (user: any) => void;
  closeTalentProfile: () => void;
  surveyModalConfig: any;
  openSurveyModal: (course: any, type?: string, learner?: any) => void;
  closeSurveyModal: () => void;
  theme: string;
  toggleTheme: () => void;
  setTheme: (theme: string) => void;
  language: string;
  toggleLanguage: () => void;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  tDomain: (domain: string) => string;
  tStatus: (status: string) => string;
  tDelivery: (delivery: string) => string;
  localizeCourse: (course: any) => any;
};
